#!/bin/sh

case "$1" in
  start)
	printf "Starting r61520fb: "
	/sbin/modprobe r61520fb
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
  stop)
	printf "Stopping r61520fb: "
	/sbin/rmmod r61520fb
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
