#!/bin/sh

GPIO=3

case "$1" in
  start)
	printf "Starting heartbeat LED: "
	if [ ! -d /sys/class/gpio/gpio$GPIO ]; then
		echo $GPIO > /sys/class/gpio/export
	fi
	echo out > /sys/class/gpio/gpio$GPIO/direction
	while true; do echo 1 > /sys/class/gpio/gpio$GPIO/value; sleep 0.1; echo 0 > /sys/class/gpio/gpio$GPIO/value; sleep 1; done &
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
  stop)
	printf "Stopping heartbeat LED: "
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

